Repository SOPT-32ND-APP4-Karrot/Carrot_AOS, pull requests merged in 2023-05, with the labels that each got.

#11 Feature/#10 chat view design
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sumin/android/carrot_aos/presentation/chat/ChatActivity.kt
  app/src/main/res/drawable/shape_gray_1_fill_20_rect.xml
  app/src/main/res/drawable/shape_gray_1_fill_21_rect.xml
  app/src/main/res/drawable/shape_gray_2_stroke_3_rect.xml
  app/src/main/res/drawable/shape_image_fill_4_rect.xml
  app/src/main/res/drawable/shape_light_green_fill_19_rect.xml
  app/src/main/res/drawable/shape_light_skyblue_11_rect.xml
  app/src/main/res/drawable/shape_orange_fill_20_rect.xml
  app/src/main/res/layout/activity_chat.xml
  app/src/main/res/layout/item_chat_announcement.xml
  app/src/main/res/layout/item_chat_left.xml
  app/src/main/res/layout/item_chat_right.xml
  app/src/main/res/values/strings.xml
Labels: 💛지현, ui

#8 [ui] 버튼 default 스타일 설정
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: ☘️수민, ui, fix

#9 feature/#4 sale view design
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sumin/android/carrot_aos/data/model/response/SaleUserIdResponse.kt
  app/src/main/java/com/sumin/android/carrot_aos/data/service/SaleService.kt
  app/src/main/java/com/sumin/android/carrot_aos/presentation/sale/SaleActivity.kt
  app/src/main/java/com/sumin/android/carrot_aos/presentation/sale/SaleApiFactory.kt
  app/src/main/java/com/sumin/android/carrot_aos/presentation/sale/SaleUserIdAdapter.kt
  app/src/main/res/drawable/ic_sale_back.xml
  app/src/main/res/drawable/ic_sale_bluerectangle_ad.xml
  app/src/main/res/drawable/ic_sale_bluerectangle_saleid.xml
  app/src/main/res/drawable/ic_sale_exmpic.png
  app/src/main/res/drawable/ic_sale_exmpic2.png
  app/src/main/res/drawable/ic_sale_exmpic3.png
  app/src/main/res/drawable/ic_sale_exmpic4.png
  app/src/main/res/drawable/ic_sale_heart_default.xml
  app/src/main/res/drawable/ic_sale_heart_filled.xml
  app/src/main/res/drawable/ic_sale_home.xml
  app/src/main/res/drawable/ic_sale_middle_list.xml
  app/src/main/res/drawable/ic_sale_share.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_sale.xml
  app/src/main/res/layout/item_recommendation.xml
  app/src/main/res/layout/item_userid.xml
Labels: 👻준희, ui

#13 Feature/#12 review view design
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sumin/android/carrot_aos/presentation/review/ReviewActivity.kt
  app/src/main/res/drawable/ic_review_card_text_dot.xml
  app/src/main/res/drawable/img_review_card_lightyellow.png
  app/src/main/res/drawable/img_review_card_mint.png
  app/src/main/res/drawable/shape_lightyellow_fill_20_rect.xml
  app/src/main/res/drawable/shape_mint_fill_20_rect.xml
  app/src/main/res/drawable/shape_orange_fill_6_rect.xml
  app/src/main/res/layout/activity_review.xml
  app/src/main/res/layout/item_item_review_card_text.xml
  app/src/main/res/layout/item_review_button.xml
  app/src/main/res/layout/item_review_card.xml
  app/src/main/res/layout/item_review_title.xml
Labels: 💛지현, ui

#19 [feat] review 뷰 기능 개발
  app/src/main/java/com/sumin/android/carrot_aos/data/entity/ApiFactory.kt
  app/src/main/java/com/sumin/android/carrot_aos/data/entity/ChatApi.kt
  app/src/main/java/com/sumin/android/carrot_aos/data/model/request/ReviewRequest.kt
  app/src/main/java/com/sumin/android/carrot_aos/data/model/response/ReviewResponse.kt
  app/src/main/java/com/sumin/android/carrot_aos/data/service/ChatService.kt
  app/src/main/java/com/sumin/android/carrot_aos/data/service/ReviewService.kt
  app/src/main/java/com/sumin/android/carrot_aos/presentation/chat/ChatActivity.kt
  app/src/main/java/com/sumin/android/carrot_aos/presentation/review/ReviewActivity.kt
  app/src/main/java/com/sumin/android/carrot_aos/presentation/review/ReviewAdapter.kt
  app/src/main/java/com/sumin/android/carrot_aos/presentation/review/ReviewCardAdapter.kt
  app/src/main/java/com/sumin/android/carrot_aos/presentation/review/ReviewViewModel.kt
  app/src/main/res/layout/activity_chat.xml
  app/src/main/res/layout/activity_review.xml
  app/src/main/res/layout/item_review_button.xml
  app/src/main/res/layout/item_review_card.xml
  app/src/main/res/layout/item_review_title.xml
  app/src/main/res/values/strings.xml
Labels: 💛지현, feat

#24 Update README.md
  README.md
Labels: 👻준희, add

#21 [ui] home 뷰 구현
  app/src/main/res/drawable/img_home_ad.png
  app/src/main/res/drawable/shape_gray_1_fill_8_rect.xml
  app/src/main/res/drawable/shape_gray_2_line_4_rect.xml
  app/src/main/res/drawable/shape_orange_fill_4_rect.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_home.xml
  app/src/main/res/values/shapes.xml
Labels: ☘️수민, ui
